jobname: historical
queue: normal
walltime: 1:40:00
storage:
  gdata:
    - hh5

# note: if laboratory is relative path, it is relative to /scratch/$PROJECT/$USER
laboratory: access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /g/data/access/payu/access-esm/bin/coe/um7.3x
      input:
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/OCFF_1849_2015_ESM1.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/BC_hi_1849_2015_ESM1.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/scycl_1849_2015_ESM1_v4.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/aerosol/global.N96/2021.06.22/Bio_1849_2015_ESM1.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/aerosol/global.N96/2020.05.19/biogenic_351sm.N96L38
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/aerosol/global.N96/2020.05.19/sulpc_oxidants_N96_L38
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/aerosol/global.N96/2020.05.19/DMS_conc.N96

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/forcing/global.N96/2021.06.22/ozone_1849_2015_ESM1.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/forcing/resolution_independent/2021.06.22/volcts_cmip6.dat

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/forcing/resolution_independent/2021.06.22/TSI_CMIP6_ESM_v2

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/land/biogeochemistry/global.N96/2021.06.22/Ndep_1849_2015.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/historical/atmosphere/land/vegetation/global.N96/2024.07.04/cableCMIP6_LC_1850-2015.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/land/soiltype/global.N96/2020.05.19/qrparm.soil_igbp_vg
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/land/vegetation/global.N96/2020.05.19/cable_vegfunc_N96.anc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/land/biogeochemistry/resolution_independent/2020.05.19/modis_phenology_csiro.txt
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/land/biogeochemistry/resolution_independent/2020.05.19/pftlookup_csiro_v16_17tiles_wtlnds.csv
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/land/biogeophysics/resolution_independent/2020.05.19/def_soil_params.txt
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/land/biogeophysics/resolution_independent/2020.05.19/def_veg_params.txt
        
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_sw_hadgem1_6on
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/spectral/resolution_independent/2020.05.19/spec3a_lw_hadgem1_6on

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/atmosphere/grids/global.N96/2020.05.19/qrparm.mask
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/grids/resolution_independent/2020.05.19/vertlevs_G3

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/atmosphere/stash/2020.05.19/
    - name: ocean
      model: mom
      ncpus: 180
      exe: /g/data/access/payu/access-esm/bin/coe/mom5xx
      input:
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/biogeochemistry/global.1deg/2020.05.19/dust.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_press_monthly_om1p5_bc.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/share/ocean/biogeochemistry/global.1deg/2024.07.12/bgc_param.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/unused/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_fice_monthly_om1p5_bc.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/unused/ocean/biogeochemistry/global.1deg/2020.05.19/ocmip2_xkw_monthly_om1p5_bc.nc

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/tides/global.1deg/2020.05.19/roughness_amp.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/tides/global.1deg/2020.05.19/tideamp.nc

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/grids/mosaic/global.1deg/2020.05.19/grid_spec.nc
        
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ocean/shortwave_penetration/global.1deg/2020.05.19/ssw_atten_depth.nc

    - name: ice
      model: cice
      ncpus: 12
      exe: /g/data/access/payu/access-esm/bin/coe/cicexx
      input:
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ice/grids/global.1deg/2020.05.19/kmt.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ice/grids/global.1deg/2020.05.19/grid.nc

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/ice/climatology/global.1deg/2020.05.19/monthly_sstsss.nc

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/grids.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/areas.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/grids/global.oi_1deg.a_N96/2020.05.19/masks.nc

        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1t_to_cice_CONSERV_DESTAREA.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc
        - /g/data/tm70/sw6175/esm1p5-input-restructure/restructured-inputs/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2020.05.19/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc

collate:
   exe: /g/data/access/payu/access-esm/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /g/data/vk83/experiments/inputs/access-esm1p5/modern/historical/restart

calendar:
    start:
        # Check also 'MODEL_BASIS_TIME' in atmosphere namelists,
        # 'inidate' in ice namelists
        year: 1850
        month: 1
        days: 1

    runtime:
        years: 1 # NOTE: Must be 1 year for land use changes
        months: 0
        days: 0

# Increase to run multiple years in a single submission
runspersub: 1

userscripts:
    # Apply land use changes after each run
    run: ./scripts/update_landuse_driver.sh

stacksize: unlimited

qsub_flags: -W umask=027
