jobname: pre-industrial
queue: express
walltime: 0:30:00
ncpus: 112

model: access

runspersub: 5

# TODO: Should be a relative path so repository is portable
# laboratory: ../..
laboratory: /short/v45/aph502/access-esm

submodels:
    - name: atm
      model: um
      ncpus: 16
      exe: /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/bin/csiro/um_hg3.exe-20190129_15
      input:
        - /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/input/pre-industrial/atm

    - name: ocn
      model: mom
      ncpus: 84
      exe: /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/bin/csiro/fms_ACCESS-CM.dec18
      input:
        - /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/input/common/ocn

    - name: ice
      model: cice
      ncpus: 12
      exe: /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/bin/csiro/cice4.1_access-mct-12p-20180108
      input:
        - /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/input/common/ice

    - name: cpl
      model: oasis
      ncpus: 0
      input:
        - /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/input/common/cpl

restart: /short/w35/saw562/scratch/access-esm/access-esm1.5-cmip6/payu/archive/pre-industrial/restart000

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 0
        months: 0
        days: 1

# userscripts:
#     setup: ./setup.sh

stacksize: unlimited
# mpirun: --mca orte_base_help_aggregate 0 -mca rmaps_base_mapping_policy '' --mca mpi_paffinity_alone 1 --output-filename stdout.rank
archive: true
modules:
    - openmpi/1.10.7
