jobname: historical
queue: normal
#walltime: 1:40:00
walltime: 0:02:00
project: w35

# note: if laboratory is relative path, it is relative to /scratch/$PROJECT/$USER
laboratory: access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /g/data/access/payu/access-esm/bin/coe/um7.3x
      input:
        - /g/data/access/payu/access-esm/input/historical/atmosphere
        - /g/data/access/payu/access-esm/input/pre-industrial/atmosphere

    - name: ocean
      model: mom
      ncpus: 132
      exe: /g/data/access/payu/access-esm/bin/coe/mom5xx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/common
        - /g/data/access/payu/access-esm/input/pre-industrial/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /g/data/access/payu/access-esm/bin/coe/cicexx
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /g/data/access/payu/access-esm/input/pre-industrial/coupler

collate:
   exe: /g/data/access/payu/access-esm/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /g/data/access/payu/access-esm/restart/pre-industrial

calendar:
    start:
        # Check also 'MODEL_BASIS_TIME' in atmosphere namelists,
        # 'inidate' in ice namelists
        year: 1850
        month: 1
        days: 1

    runtime:
        years: 1 # NOTE: Must be 1 year for land use changes
        months: 0
        days: 0

# Increase to run multiple years in a single submission
runspersub: 1

userscripts:
    setup: ./scripts/pre.sh # Update land use in the start dump
    run: ./scripts/post.sh # Update land use after the run

stacksize: unlimited

qsub_flags: -W umask=027
