jobname: pre-industrial
queue: express
walltime: 0:30:00

# note: if laboratory is relative path, it is relative to /short/$PROJECT/$USER
laboratory: /scratch/p66/hxw599/access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /scratch/p66/hxw599/access-esm/scripted_version/exp/PI-test8/Running.dir/um7.3x
      #exe: /scratch/p66/hxw599/access-esm/build_v02/bin/um_hg3.exe
      input:
        - /scratch/p66/hxw599/access-esm/input/atmosphere-2

    - name: ocean
      model: mom
      ncpus: 84
      exe: /scratch/p66/hxw599/access-esm/scripted_version/exp/PI-test8/Running.dir/mom5xx
      #exe: /scratch/p66/hxw599/access-esm/build_v02/bin/mom5xx
      input:
        - /scratch/p66/hxw599/access-esm/input/ocean/common
        - /scratch/p66/hxw599/access-esm/input/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /scratch/p66/hxw599/access-esm/scripted_version/exp/PI-test8/Running.dir/cicexx
      #exe: /scratch/p66/hxw599/access-esm/build_v02/bin/cice4.1_access-mct-12p-20200218
      input:
        - /scratch/p66/hxw599/access-esm/input/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /scratch/p66/hxw599/access-esm/input/coupler

collate:
   exe: /scratch/p66/hxw599/access-esm/raijin/mppnccombine
   restart: true
   mem: 4GB

restart: /scratch/p66/hxw599/access-esm/raijin/restart

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 1

stacksize: unlimited

shortpath: /scratch/p66

mpi:
    module: openmpi/4.0.2

qsub_flags: -W umask=027 -l storage=gdata/hh5+gdata/p66
    

