jobname: pre-industrial
queue: normal
walltime: 3:10:00

# note: if laboratory is relative path, it is relative to /short/$PROJECT/$USER
laboratory: /scratch/p66/hxw599/access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /scratch/p66/hxw599/packed_up/bin/um7.3x
      input:
        - /scratch/p66/hxw599/packed_up/input/atmosphere

    - name: ocean
      model: mom
      ncpus: 84
      exe: /scratch/p66/hxw599/packed_up/bin/mom5xx
      input:
        - /scratch/p66/hxw599/packed_up/input/ocean/common
        - /scratch/p66/hxw599/packed_up/input/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /scratch/p66/hxw599/packed_up/bin/cicexx
      input:
        - /scratch/p66/hxw599/packed_up/input/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /scratch/p66/hxw599/packed_up/input/coupler

collate:
   exe: /scratch/p66/hxw599/packed_up/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /scratch/p66/hxw599/packed_up/restart

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 1

stacksize: unlimited

shortpath: /scratch/p66

mpi:
    module: openmpi/4.0.2

qsub_flags: -W umask=027 -l storage=gdata/hh5+gdata/p66
