jobname: pre-industrial
queue: normal
walltime: 24:00:00

# note: if laboratory is relative path, it is relative to /short/$PROJECT/$USER
laboratory: /scratch/p66/hxw599/access-esm
model: access

submodels:
    - name: atmosphere
      model: um
      ncpus: 192
      exe: /scratch/p66/hxw599/access-esm/build_environment/build/um/um_hg3.exe
      input:
        - /scratch/p66/hxw599/access-esm/input/atmosphere

    - name: ocean
      model: mom
      ncpus: 84
      exe: /scratch/p66/hxw599/access-esm/build_environment/build/mom/mom5x
      input:
        - /scratch/p66/hxw599/access-esm/input/ocean/common
        - /scratch/p66/hxw599/access-esm/input/ocean/pre-industrial

    - name: ice
      model: cice
      ncpus: 12
      exe: /scratch/p66/hxw599/access-esm/build_environment/build/cice/cice-12p
      input:
        - /scratch/p66/hxw599/access-esm/input/ice

    - name: coupler
      model: oasis
      ncpus: 0
      input:
        - /scratch/p66/hxw599/access-esm/input/coupler

collate:
   exe: /short/public/access-esm/payu/bin/mppnccombine
   restart: true
   mem: 4GB

restart: /short/public/access-esm/payu/restart/pre-industrial

calendar:
    start:
        year: 101
        month: 1
        days: 1

    runtime:
        years: 1
        months: 0
        days: 0

runspersub: 7

stacksize: unlimited

qsub_flags: -W umask=027
