format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe:
  fullpath: /scratch/p66/hxw599/access-esm/build_environment/build/um/um_hg3.exe
  hashes:
    binhash: b7e2b21b20e1e115c303ab887989cc81
    md5: fe7a29a4a892d67af0015c24f7dfe48c
work/ice/cice-12p:
  fullpath: /scratch/p66/hxw599/access-esm/build_environment/build/cice/cice-12p
  hashes:
    binhash: 6149791d950d3ac29d08f42c37b520d8
    md5: ea56d8419c59afe03f47fd77cc7b30ca
work/ocean/mom5x:
  fullpath: /scratch/p66/hxw599/access-esm/build_environment/build/mom/mom5x
  hashes:
    binhash: c9905c0996aab37ee796f67324b2f129
    md5: 33beab1f9ea72a83261dfc35d8569014
