format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/atmosphere/restart_dump.astart
  hashes:
    binhash: 1ddf21de339215a214957deb974d69f7
    md5: db9fcbd3a483be89516a9a6f8b1dda7d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/atmosphere/um.res.yaml
  hashes:
    binhash: a6012f8ec14705bb7734ed905b653561
    md5: 6705b4a77196deadc20615da2c6a3ce1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/coupler/a2i.nc
  hashes:
    binhash: 26880a427b984176d8f573f7347d3e66
    md5: 75b4d2d784eabbe6a0a481dbee20bab4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/coupler/i2a.nc
  hashes:
    binhash: c0c6f2bc3aaa0cbb079c493123e6bf63
    md5: b7a94292361235aa7766964f8d966b77
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/coupler/o2i.nc
  hashes:
    binhash: 4fc07823bfac9b29a801d937723a4df2
    md5: ced9e11a31cdfa42b022b46775ef4c0f
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/README
  hashes:
    binhash: 630b6acd3fea02c21a02a34df31b2878
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/cice_in.nml
  hashes:
    binhash: da6edb0d97d74805d62963a7b6b64118
    md5: b339a517542a847a66f97adf76a0a0b4
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/ice.restart_file
  hashes:
    binhash: f2ff71108a249c7a4b007cd3927d061a
    md5: 84d63670c1919bcfed65b161895c1eeb
work/ice/RESTART/iced.19180101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/iced.19180101
  hashes:
    binhash: 6954f78bda04fcb274c74681f0c3a313
    md5: 6babb4ebce51980b48ae69e6a1f363c8
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/input_ice.nml
  hashes:
    binhash: e1db69fc8c9e4bbacab89dc0a161696c
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/mice.nc
  hashes:
    binhash: 07ac840fff03bd92d0b6454d54c72f14
    md5: 0a73b02c44a30db06c856bb4bb769cf7
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ice/restart_date.nml
  hashes:
    binhash: 96a73dcc62d79677b48a524e297d7352
    md5: 80c1fac9186e338d10929299e6a4b88e
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 0a3b24dee45fda6a1249689966c7e764
    md5: f85f8b125e896e5b1266fe30ca7c53aa
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 3907490a01efaccff388d3b3afce9003
    md5: 12cda51aff5cc12b88c0a22bd9745376
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_age.res.nc
  hashes:
    binhash: 56803f5d4f78d18656c38d82b6ef3b7b
    md5: a9fb514a357e4c08e95c178c88cce300
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f935436ecb414a6767bc4e1a2d9662f
    md5: 9bb75609295aa52b60b78475efdfedd9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 676d6b8c3738c5031d245e53f001bd83
    md5: a846a57be535d2e63ad260c9c4e2ee7b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_density.res.nc
  hashes:
    binhash: 04097190012a255f5be13ccf54231d2a
    md5: 04487c349ef81574a0f69d6fb082ad52
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 873d21b867a3f0963fc0bb1144566f8b
    md5: 617f9b1c0ee3090a16ab2a7ec3a6986d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b83014a6900cabe7264886363a490e21
    md5: 102713c49968fcab794b11a3d338ee24
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1a1a7f1cb833ebbbdcc9875ccd5e22a2
    md5: 635b0826f09b7a6dd53fe3a2782110f8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 85a9510e48b73e3343d22514a4b886c0
    md5: fe4437ff8e6a45662b0b89608b405e4c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0eec4f1f6f88b3cd01ec7bfe177f43d6
    md5: 0185b8139af24aee0a0e7fa1c797032b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 763e86c6a1978aa9b559348d84db53d7
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_solo.res
  hashes:
    binhash: c89826075d58af2334cdadf09176799c
    md5: a811bf7b1abbbdabbc3ce147996dd949
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9eac2abc8ccd78f8851d33a34bf59a0b
    md5: a6f09c6514d6f2ad0a484145e2c2bdbc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a8cb6d929d46c0d45b8577e1cb9c4dff
    md5: 19da2b75aea3540c4983a6bb6507ff93
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_tracer.res
  hashes:
    binhash: 814b6399013993b4f2b03443c9c14caa
    md5: a04332df2f0110471f0513abf42454de
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4aff6696fcabb17e00459effc6c7d868
    md5: d8d3904c1c2b720cbf0676a5b4675bcb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart067/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 789c3506c40337ca3bf47c6c6840b7e5
    md5: a22882a3cdef2a51314d3679be75b904
