format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/atmosphere/restart_dump.astart
  hashes:
    binhash: c49b0bc63cb36d5e8a67ff1247a5300a
    md5: 0cbadf39a93b7dba8745cbada7a94c80
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/atmosphere/um.res.yaml
  hashes:
    binhash: c868831e5d53157f5aa6407bf0069380
    md5: 3982e1d9286d22649fcfff41011eea60
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/coupler/a2i.nc
  hashes:
    binhash: b846a2234c89b461615b6890f9e48e7e
    md5: cb723d6aaf1de8badacf0847ab64da60
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/coupler/i2a.nc
  hashes:
    binhash: eb6a330a6831fe062068dbbf7826c008
    md5: b419153bae8bfd5a9a7fc3aba311289d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/coupler/o2i.nc
  hashes:
    binhash: 7b3cef4623213f1e2d93f6e8d3c33229
    md5: 36333d4609d7962397612f6617f92edb
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/README
  hashes:
    binhash: 59e4adb629b16bee64e4473621d15664
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/cice_in.nml
  hashes:
    binhash: 08ebc2cd2ff8b9dee913c724d14db946
    md5: ce1affdb9027e566c80a520935b6b2b4
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/ice.restart_file
  hashes:
    binhash: 785c427dc941876d39b3a23528704b3f
    md5: db3483dac06a6e8b7c6d5d1cc737865b
work/ice/RESTART/iced.19280101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/iced.19280101
  hashes:
    binhash: 701d291772ccc71053deeb55598a0273
    md5: 3a4d8b8886983354eedc42dc190313d2
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/input_ice.nml
  hashes:
    binhash: db92935c3cc696faf70d220a7882f9f2
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/mice.nc
  hashes:
    binhash: cbcea6c2ead78c00218ae30be4528a8b
    md5: 0f1318fc435d5d720771b5ba925f3c6a
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ice/restart_date.nml
  hashes:
    binhash: fcf528cf13c015380ed1c6fcb3e3875f
    md5: c7e0b9eb0364c6a5a2d58cf2739b19d3
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 0d9e6b45f57d73062d24f519a00b2ac7
    md5: cbe099c208754ea1e9c95ab7a906949d
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 7861269ede0754fb4cb2b6508121bd8f
    md5: 03cfc1ade34de669b8629f85f0a57cbc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_age.res.nc
  hashes:
    binhash: 4368562a16248ed6b387843b6ff6a3e9
    md5: 3eee6b6e682ea5b9aba0d8d513831ddf
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 84bcd082cf9ef19b508d21988013b0c9
    md5: 53db21fb11d566cb6d43276b6083c70c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a454606c97ad8fa54eaa790bc720d42f
    md5: 8fc0c4e450d9a66a3c5e22958e5f847a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_density.res.nc
  hashes:
    binhash: 0da2f758688e6f18e4e272f77900137e
    md5: ba6f311b957f250b3607764d46179f79
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a2d28fd43ebc2affbe7c44b2dce701ee
    md5: 6873cd3cbfd09333a707f83930e8963d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ee560fa0fb1ddbc9cef8384332095ff1
    md5: 6dd17a6bb0075fc9fe3624db1c4b3104
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 40b480d5ea21d1b20584122672a227f9
    md5: e4afc811ecbc0df3f20025b30c47e6e0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b890e2da6c30d74a2001f361ad5bd539
    md5: 253637395f22e536cd1b20fcae3f40e5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c4c3317162b1f41e366ac3eabe990d38
    md5: 1070a7bd5ea1dbf0fdc1987ae40ccfc0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2c9a7b0b765a6f686a3f835da46de4e0
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_solo.res
  hashes:
    binhash: 99dff619e15fc3f880857a9e2af2164b
    md5: df6a0e31b4485b07189617e0b14fa24d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 813ee60b77b58e4dea4f2ca7fffba4f9
    md5: 767f7647f9193fd474abbc985d78555f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9333866eb2460b863bf3175867c75410
    md5: e13abbe67d8d0eea9505f6fe91ed3f47
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_tracer.res
  hashes:
    binhash: 50dd3e3e4fb5d55d7f7782617391e28a
    md5: df9daf3627c27850e872aded589e129f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 128ac2802633651f8240f6bcaea7478b
    md5: 49049b9f037def47bc1bbcf83fce656b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart077/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 17560a0ef444500b6ea8e855847a5503
    md5: bd0fac3c5f2a2767620b34d29ca499d3
