format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/atmosphere/restart_dump.astart
  hashes:
    binhash: 8b2e570ba58795a0a1fb52a2b76d3dbd
    md5: 81e9d57d92b54665796fd3ab9882e39c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/atmosphere/um.res.yaml
  hashes:
    binhash: 6452589a7ecfda5ebc248b2e86b753c8
    md5: 85874b69ed6dc9ca29d6c9f3e0a20fad
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/coupler/a2i.nc
  hashes:
    binhash: 0268c2c338584021173a0bce42725f45
    md5: b2bad4669c5eea26f42c7128bd142985
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/coupler/i2a.nc
  hashes:
    binhash: 5889d11a7a7cb293abed6a3e8393b0d2
    md5: 2bc386ffb6031db4a7d2558d32630f11
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/coupler/o2i.nc
  hashes:
    binhash: dedf33657cf72bc69130acd6f477cd27
    md5: 02e727bdf71e11fe045348e992cccd5c
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/README
  hashes:
    binhash: f2eb3328ed1c0b11a6bb008788c49085
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/cice_in.nml
  hashes:
    binhash: 906991a43e63ebe9d995c779c9f30165
    md5: df2cd1cf55e7f1f41e6498053b2175c7
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/ice.restart_file
  hashes:
    binhash: 7ab430a5909f3749e173640f2915fae5
    md5: a69221101ddd9febde62126dda9d3668
work/ice/RESTART/iced.19140101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/iced.19140101
  hashes:
    binhash: 25386e79924e869427ac380220e7d2d2
    md5: cf517985b656d82f0775ee4c93f435b0
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/input_ice.nml
  hashes:
    binhash: a6f8fc11fa39197d0362153d9723a53a
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/mice.nc
  hashes:
    binhash: b8fed250a2e5f908a0995fcdf4cf6bd9
    md5: fdf20e14b2bd60e5bc267214ac74466f
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ice/restart_date.nml
  hashes:
    binhash: 5d73096f400aee7b6ee180608a048a86
    md5: 1b86eff0799ffa8268ad6d38aae2a34c
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/csiro_bgc.res.nc
  hashes:
    binhash: e47f54703a00742b367294119e9f9993
    md5: dbddc62a12e4efa9167b03cd42ea6ca4
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: bbb7485dacc93cbdf8bfe6b7be10daf0
    md5: f078e2e6e4d6e4fe016db9787a7429c4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_age.res.nc
  hashes:
    binhash: ddfd4c7a1b8ac59d648e77c652f4e4a6
    md5: bca93513edaf775a819a1f24976fd518
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 858b8ac81a82f3fa6f5581a674e3cbaa
    md5: 5333d998814f36ef144ef04d7f27d071
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2965fa675abc00db9189ea9183422e3a
    md5: 97c4d5fd3bcf917c18086c4c7da44a27
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_density.res.nc
  hashes:
    binhash: 93a2198a2b0212064c7246ba137beead
    md5: a08f12ee943dbd06bcfcd5fe31aab9e6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bc364f9016540f213713d7a7bc179c32
    md5: 9f5d85fd6253d7dc87c51bba22f0b2ed
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 671f8c5c61e32f849148cd778dbca53b
    md5: 7a8f6ac4066b77d6bbef508d5b7af34b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b2d8626524bf7579bd914915f721a44d
    md5: 90e3c9725fa5476078023c569ef61412
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4f456c7a73cf07fbd2a534dd42de3cc0
    md5: 3979a0440abf81953251949955492896
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5989e120025047fcb826adc13ff8450d
    md5: b55ab9e1c7d9ae7ef9c441218b08a57f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b63001d46884c83a41c9f3b8072743ef
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_solo.res
  hashes:
    binhash: 3d7eaad542c18aa12f62940ebd154897
    md5: 745f79979aef3a02d63b963f1c04d596
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e0c686ef481f795b401b70c26b2b3784
    md5: 78d7d2fb468c7f7dbd3d758616476f79
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d58714387bc186377ba0c4d8c97e3a82
    md5: 4dd1801b3d66744ed90404d7a7c5d02b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_tracer.res
  hashes:
    binhash: e6362c2c3a97564d93da1711ac274c5f
    md5: 681c215c338b7f8ac6b962a4a956d8fd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3567532ddc27d51adebc7e09ba976577
    md5: 994492041893e6119827622c1acb270a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart063/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4398126f78b6c07ad0af73f348f6b10c
    md5: 4e94964a35d9301c36b3a25f0d10907a
