format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/atmosphere/restart_dump.astart
  hashes:
    binhash: 75aa600f11e2dfac797f58889a41deae
    md5: 163b42ecf3fceba864283fec48fbc3a7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/atmosphere/um.res.yaml
  hashes:
    binhash: 5f7caee064a72cc98d148a0eb06eea25
    md5: f9e737be4efef8df126e9275f790ee13
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/coupler/a2i.nc
  hashes:
    binhash: c156c7716ee9b7850c88b0ff0b2414e8
    md5: 1eaee5a5cf918852f569d2a5b5011e95
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/coupler/i2a.nc
  hashes:
    binhash: 90c58abe24bb4cc57d2bbff798602107
    md5: 6cdcd1f86f26ee05773834882d82c0d6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/coupler/o2i.nc
  hashes:
    binhash: a1aac7ab96533471707e5b1399b912d5
    md5: 98fda184e7ac90ec01095ff3d82e8abe
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/README
  hashes:
    binhash: be41eff1e2bd37aa57a7440a417f33fd
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/cice_in.nml
  hashes:
    binhash: 3bef9c770e9a69ba182f2b8339d49052
    md5: fbe7254e294b8c83d5e08ed4bd558283
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/ice.restart_file
  hashes:
    binhash: 47ca23fe6a17568fe352bfe865c63150
    md5: bec1f50b210940d21f54d4958ed8d871
work/ice/RESTART/iced.18910101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/iced.18910101
  hashes:
    binhash: e8bbaedbc095535c99cfecc7f82e6892
    md5: 564d51a71927465c5d853090246dc5ce
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/input_ice.nml
  hashes:
    binhash: 75be9bd280b3d30e3070379cadccb6b7
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/mice.nc
  hashes:
    binhash: b7bddf30f4064e78f7a6ee8dbf87e13a
    md5: 017fad4822d44253c56cc75bd66e5250
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ice/restart_date.nml
  hashes:
    binhash: eb3c35762cc9e559230863b9370480df
    md5: db5e197e08f767814ab6441b9fcef2b5
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 17c6a5346c19b1f48897486ecc6d4a15
    md5: 9f80bbd321f96f98bc1ab4962df70ce5
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: aea75b185c0e3c80b3d8926d7d73f3ea
    md5: 244f4021e31fd537f62dd872048807e5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_age.res.nc
  hashes:
    binhash: 9b32f30c289d979a8b0063f9319799c1
    md5: e85ae24872cd4b39377c23c7efe30412
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c764d54b31b6259a9f618a8bde79a1bd
    md5: addb42e79e9bf080117f267464beb1a6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c197b7c64287ea85b441dd2a1a1f9f5f
    md5: c647d54166b52d5c256d5b4e2f88a849
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_density.res.nc
  hashes:
    binhash: 6f710e67e32b145c4095cf090d770ef6
    md5: 962841b2b3abcd276033d97499086040
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 62996bad503d60da52be9c47fda502f8
    md5: a4c0403d34cdec56fe4c410a810a6eac
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: babdc6eb38cfedc7746622a16c8473f1
    md5: 092aba975f6a38e244a29f4454c3d19f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6b86d8cfd32f83139454e0a390d0bff4
    md5: aa115015d8419bc65dde20610b7e5854
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5140bedfa7d6bbf00c97569dfce71da6
    md5: e702ffe15b0f2145211aacf078e4818c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 731ca4fbba00782fcc6813ef3feda87d
    md5: 5847b5a2d915844c4b4c72e42366bf53
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 35f8cff5258001ed88eca11d1ee05912
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_solo.res
  hashes:
    binhash: bfa0b54a749ec9bd481b5e7754b410c6
    md5: 4e8d362a7cfedfff0aecb6e8fd428aa7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5d58d7a98c870a8f776d4f3609220e04
    md5: 8349ba958aef149df1b4e316631a29c9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c94d25ed0a1bb114e6e9f14ca7a8d453
    md5: 148d6eecec68a03b850356e5304b2fbc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_tracer.res
  hashes:
    binhash: e94437955d78dd65a5de6a47e989280a
    md5: cbd4fa1428bd9d897dc14c7a3af8f384
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7e30a5e452b33b77df782e97896dad4f
    md5: 3b4020168af862f10e43c73814faf88a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart040/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2518cf3094b38f310daa883408fbea0e
    md5: 3d5aa92ebe2f79f6d8b9510a5cd8e98b
