format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/atmosphere/restart_dump.astart
  hashes:
    binhash: 2560c6775600bb36fa13685f00df02c2
    md5: 811b3ab270486b9c92c6e8c7ff0da093
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/atmosphere/um.res.yaml
  hashes:
    binhash: 4b66f1fc0dc96228ff94150bc28affe8
    md5: 5b47267909dcb23352a08d13f6575c83
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/coupler/a2i.nc
  hashes:
    binhash: be71dbb2ef8462f9c6f0bf029ef220c0
    md5: 316c54d02248daf403e355e92b430e9e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/coupler/i2a.nc
  hashes:
    binhash: 99cd84cd7c2594c696f125a01274f906
    md5: 975caa91bd803bf409b9bb7b53727831
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/coupler/o2i.nc
  hashes:
    binhash: 5269bbd96a9affe055e4229b7e722109
    md5: 8de1fa2ddc4f3dc3199d12ad9ecfe6b6
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/README
  hashes:
    binhash: 7d7ba00c9a36cef27b8c4f3e0c7e8243
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/cice_in.nml
  hashes:
    binhash: 09cdc531f8a1d55d4bdb6724aab8dc80
    md5: c47bd97ee966e382f2f8c22e91be4adf
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/ice.restart_file
  hashes:
    binhash: 737f9a6ffc3be463c10db75697d5c2d3
    md5: dd8f13671a8d9e930a169879cef92a10
work/ice/RESTART/iced.19480101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/iced.19480101
  hashes:
    binhash: d3bb6ca9b6d48742f490f6b96e8ff233
    md5: b7222cc62ea6012211526096a0db79dc
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/input_ice.nml
  hashes:
    binhash: 58d02230123f4c40e8bb9156775ab420
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/mice.nc
  hashes:
    binhash: 4a11a9e8b58e40776cc6ba12c2192fb2
    md5: 11545858c0980a6cefd75fecbec4a8ba
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ice/restart_date.nml
  hashes:
    binhash: bb3596d7826e7305f127b2488888ef7d
    md5: 5a72e77ed08737a8f694df87a6aedf08
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/csiro_bgc.res.nc
  hashes:
    binhash: fa58b6f79ffe9c5e378ed178ffe2f5d4
    md5: cad06fc46bdeb674b0c27c5ef35a8ccf
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 6960428f1ac7aceeb7f6741e2844e7f0
    md5: 3728c2dbcf8e58bedb877ad8a7422522
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_age.res.nc
  hashes:
    binhash: 9e399cea936018d1de016b527d3a1381
    md5: 6da95b8a1adc03049f1b5eb1efa996fa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3d19d6671ea7df313ed89606b6db0da8
    md5: 28f4502ad7def07e375ddfa98e20efc6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bd25da6b990330f4a43ff602b415b407
    md5: 84f436015c6b5f5348be357df3e800de
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_density.res.nc
  hashes:
    binhash: 9e1abe454817f55c0a823cee4ccb4e1c
    md5: b8a53bf4f9a4fb9a833a55fc5341ceff
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c53c26d53c4d389e999770bd16b0763e
    md5: 2a045f689cceb3931bb148dad7ebc98d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fd56f78c09aeaca0d4c50244612b4b09
    md5: bc2aa6410fb082bb16c4c2babda3d427
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 22ca6b66503cd0c25e5bbf9da63f53f4
    md5: 6b6baf7ae12254b224520fe1a66ea3f2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a16af518f94f80a0acfd33dd93ac111b
    md5: a93263e492f709428cbaca1ce2a56938
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 033a2363e9db8ade3a08acc3bc2b44a4
    md5: 2ee827c1e8eede2a9240f7abaf91facf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 63012648fc752b2c04ee9d4b31e27486
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_solo.res
  hashes:
    binhash: e9a3f496205743f6eb04b67bec16a774
    md5: 9f227b3cc3a506747296ae01bbf2bc51
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 36fea4d72ac40a6be0cc4ed36b78f21a
    md5: 59bc7b008697c8b15e519307a40ea7f2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bb9a25eac22a24b096d3b83a89a56910
    md5: 6ced49e1bfa70a7ccc46a66949bfda9a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_tracer.res
  hashes:
    binhash: b2b742af4a4f7ed80f013bfb550ee81d
    md5: 3b834a879d8070fc788f13c2fc00bfa3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c0b5f3162d0d2d36c32dcf2cce43cd01
    md5: 97b94740792e3a4081efae534096c7b4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart097/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 356e1f5997bdaaafca720a52fd669d78
    md5: c5ff81c3e6d15189f723a8c427fbe283
