format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/atmosphere/restart_dump.astart
  hashes:
    binhash: ab4748821985b40553d40aa38271a708
    md5: deac97f092db81a5ad1bc2303a5bc98e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/atmosphere/um.res.yaml
  hashes:
    binhash: daa3d650578419c9afbcd8e32d83615c
    md5: f0e3ea2a996d700e781914991fb390b8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/coupler/a2i.nc
  hashes:
    binhash: 81ec297d0f3423f5dc78be4bd0bd8aaf
    md5: 7128e45c70a5b3b6a687ba863e7fc830
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/coupler/i2a.nc
  hashes:
    binhash: 77ea82e72e6fbe4a541001df7750f634
    md5: 0566f53a65f0594fc0f26e885e0b7863
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/coupler/o2i.nc
  hashes:
    binhash: fb270bd5fe16c844b961344185987a40
    md5: 7cb308acd8be73b4cb96ad1631300ac7
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/README
  hashes:
    binhash: b9428f965ce5888c27b73ba8c5c6460b
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/cice_in.nml
  hashes:
    binhash: 6c117b28c317c2a28eb1761781cc14f4
    md5: db7962644a3e1c7fbeab86f9b2822ead
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/ice.restart_file
  hashes:
    binhash: b7382ad1bf23617816367da6b5deb588
    md5: c24681db1e24cb4ca9856395f7bc2917
work/ice/RESTART/iced.18610101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/iced.18610101
  hashes:
    binhash: b29a3ccb060da3bbd899ccde7916160f
    md5: 3d33a34cfb286a43d27d350b84a32a91
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/input_ice.nml
  hashes:
    binhash: d75d2e715982596f6bf846b5de3475e3
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/mice.nc
  hashes:
    binhash: f274dc0cba1201cba7eb21c77110de3e
    md5: 8a6ea45f267dd410ac3b2f0b61e15888
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ice/restart_date.nml
  hashes:
    binhash: d51da0b59757ba6e565fef2eadafe10e
    md5: 1ee88db866e5dacb9748f2f32df69066
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 5bf90ee5d3c32810e45e4a1b6570ddd4
    md5: e767084d29cdd8465a6743d78f8f1382
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: b8fd66355d07d5d61ce822deddd7adf5
    md5: 4fb026ccde7c793c73a8e43bb750d071
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_age.res.nc
  hashes:
    binhash: 1e0e9ddbeb60ef91b53eae50b028db3c
    md5: 371a70d3af4b85543f5e1326eca5cd43
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5bc08e569daae791ca292eb963379507
    md5: ee4745ef643e3c84e3df54bb42c32dfe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bf0d8cea4a2616bd184344c746825e13
    md5: c180d51a6af2be5664bc2409ca37886d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_density.res.nc
  hashes:
    binhash: 50d7c3a9fffc83530b5d4866abf585db
    md5: c8ebf23676aae0929417f7109a23536d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8a0ef9973805524b0f8c3d7caf4e4db8
    md5: 6dd7fa7999cbcf55be9fcd077fb01398
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f1b1612b0db806c4162f9ec80cd422fe
    md5: 0e6821e4065fdcb58066a5c54b6ae59b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b3379fdbb03fff0bfb1adee003b674f4
    md5: 74ef6c8b8d258774c4d985725212e9fa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 43a935366c3c119b90603e60078b30a9
    md5: d13d729b6e268a571d321a31aae79e36
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d66eddd16b1f74c5ea2e8e5b3dd12a91
    md5: a7c4b01370da5acdb63c854262829a13
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5b1677cdd698252b0d4ebe7aac5fe70e
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_solo.res
  hashes:
    binhash: 61b8e4b28ca532970281689e3bd106d7
    md5: 6751d986938f21ed1c920e2f86dd246a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ef9e4119cf0359a8a59fab84b3fb3d3f
    md5: b5cee01a7d0f826bd182b5be3a8673be
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a116e9f578b486dfdf96c9da34ebc8a8
    md5: e962797e9eb75e1476e07fde05092b49
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_tracer.res
  hashes:
    binhash: f4523d16ec5d539f405abdb1376b6508
    md5: df050dc5ce91b3859783b6990a71e1a3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2129e19bf5da11ce3fecdfce247097f4
    md5: ccc4eb8fca5494f68a08ba5aec04d4de
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart010/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 601184ffc9a153f6c008121205552bdc
    md5: 24d41d31da1448b516ceddb6db084048
