format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/atmosphere/restart_dump.astart
  hashes:
    binhash: 23c2aa637e9b448650d74c63fef6d86c
    md5: 67d4f87c250f271079c895acde286030
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/atmosphere/um.res.yaml
  hashes:
    binhash: ec2dabbbeac18780573df434d59acfef
    md5: bfae565d73ed2d26988ee323a2ed561b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/coupler/a2i.nc
  hashes:
    binhash: 4bb2913a696ae8d186623fcd0020bb71
    md5: cc0f0c58e844f52e4f4aec28159bd4c7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/coupler/i2a.nc
  hashes:
    binhash: 0bf58717f4335ab7409440ed27f148b7
    md5: fa0057c87a7cfdf4c5dfaa18eb41567c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/coupler/o2i.nc
  hashes:
    binhash: 7a11acb585595b3f4370916f1fd5526d
    md5: 9403b97744b32934dfbd82a2b1535324
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/README
  hashes:
    binhash: 368df5cebbe19690f90bd0281b485b35
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/cice_in.nml
  hashes:
    binhash: e1d96fdfa0b5e521070c43f6cb326916
    md5: ac9763c79f2b2eaa8d56a2fe48ab9238
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/ice.restart_file
  hashes:
    binhash: 11e3159416f34d77284f1e8accdfe03d
    md5: 70a116055d1d95bc63acf4a43eccdf9a
work/ice/RESTART/iced.18800101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/iced.18800101
  hashes:
    binhash: 2d508fac3dffa118c40bf53cc23f73d9
    md5: 79187a32ad8da6568f48361079aa895b
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/input_ice.nml
  hashes:
    binhash: ff3f01cc88f2de964c01d4ea48728861
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/mice.nc
  hashes:
    binhash: c6b087bb56d48a4bf5663cdea02a6990
    md5: 5c79c988b7b5935db91071d6b5fd6e2b
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ice/restart_date.nml
  hashes:
    binhash: bd3d5a6d28ded9e6a8428ff67e25f7c8
    md5: c2c9775b7c6de5e05732883b8ad7d8ec
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 336e0a995ef93444789365957d65710c
    md5: 9cee53f6c0629750d36ca8fd39b263be
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 32091e0d868cbf63df17cd7c86095acd
    md5: cd9351dca4561b4c1e6e8aa5f8f52abf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_age.res.nc
  hashes:
    binhash: 3bdd7f6b8586599cac5e2fd2ed56991f
    md5: 5a2533908e94edc8271d624a3acf53f5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 37e40c4f0bad361babb991be76db62be
    md5: 2bf2d4502a6b5e607bee72d896a10f72
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bffedb3c6896acff9a9a41e088f5662a
    md5: 3c1bca838f8272700cfdc4f9ae6692db
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_density.res.nc
  hashes:
    binhash: 3769e8a065b05c8d9e96797275c590f6
    md5: 93a3f54c93b1534630a251ae9487468b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 272203499e16ecd4b44b14556f31280a
    md5: 51eae05f265cef974ba0bea761559d41
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6b6d81289dc8f97592a64b68652c85db
    md5: ab0401adca1afc41d759892b6bc1f12c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 40802ed1ea8b870b4db105e04ac0c3ac
    md5: a76888d4418d7c9a8ee2f31ba152ef3d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1512c9bfd1bb4fb48f86193038e4f4ea
    md5: 99ec91bc98dbc9808720250695c65fc6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_sbc.res.nc
  hashes:
    binhash: feb2a59e275c260ad1bfd048c061fc37
    md5: 9fc536fbd09acbcbf2aa0f7ee7ad0b99
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 25fd90bc839252208224e5bf6071ce4d
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_solo.res
  hashes:
    binhash: 48fb4869be33793e35eb5de7b46e3610
    md5: ae19e66a4b327537359cbe6aee63a774
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fa617ae4daacdaed5faf27b74122dea9
    md5: 4f3251a4852b1a10336ef16ba35204af
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f98cad1e5c278c930c449af2954b13b5
    md5: a0265b456321279c821bc6eac01c5e4d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_tracer.res
  hashes:
    binhash: 03601a83e5deb406bfadf19d2aa2e2ed
    md5: a0efbd9aabc01ec7fc4f7df8dc5861b5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ce78889a9104429aaa00f1ba43c0299
    md5: f3f79232a9e87853a6e338e7e566213b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart029/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 830a1223e96190ebd1af486d8dbaed3a
    md5: 6b032ae099de7479ae35be204e1a6a17
