format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/atmosphere/restart_dump.astart
  hashes:
    binhash: 4895d521cfcf47253f25b4ff0dbcc3de
    md5: 697bd14ee15788916ce19139c5102cea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/atmosphere/um.res.yaml
  hashes:
    binhash: 2f10c7f983ed2e9e2f261b125b655eba
    md5: be332faa37931a6e8778da883e50a145
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/coupler/a2i.nc
  hashes:
    binhash: 5abbbdddf294c6f16f103d745db68c6a
    md5: 656fc31252eb1d3cd7daa3c3dc466194
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/coupler/i2a.nc
  hashes:
    binhash: a0a81c9d8ee6934479c32da07d058221
    md5: 8276627b1e9330a162aeffa9b0700dff
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/coupler/o2i.nc
  hashes:
    binhash: 83707e4c7d2f29ad0f224b0794a5378c
    md5: 93d4bc33700305d622fe2ea9b2220a75
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/cice_in.nml
  hashes:
    binhash: 0f293a8ed805cfd1d1f947bc2bd00792
    md5: 7b2ab1e3d8b3c0a78ac61187103f74e3
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/ice.restart_file
  hashes:
    binhash: fb8cc5e6867a91916eec9fb4f318780b
    md5: df0884c92e4a60ca71edf7d760cef9ed
work/ice/RESTART/iced.23900201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900201
  hashes:
    binhash: e69a6dd952b9973f70d92391664c01cf
    md5: 028f4e5f358e884c9a859837c6c19a07
work/ice/RESTART/iced.23900301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900301
  hashes:
    binhash: 61b85c1f5905d522735735ad0375a4bc
    md5: 99f4a0d3d429a6e0d1c17ec629365670
work/ice/RESTART/iced.23900401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900401
  hashes:
    binhash: 297da197344a45f2f8253051c47ee6b8
    md5: cbad68b006778eea57186900d5a408c7
work/ice/RESTART/iced.23900501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900501
  hashes:
    binhash: 0afc80409655e509f4893a6d04ae7fde
    md5: e1881b3464d178e6c60309e3c2fc61a0
work/ice/RESTART/iced.23900601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900601
  hashes:
    binhash: a5ec3406c3665f69d57218ef8a03c985
    md5: bea4991a24681d37f70eaf0b054d4c3e
work/ice/RESTART/iced.23900701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900701
  hashes:
    binhash: 73638f34971a2eb73901a52a3c502c33
    md5: 36dad649c12a1b140ee700e33373320e
work/ice/RESTART/iced.23900801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900801
  hashes:
    binhash: fd108ccc8f05bf94b1e959a11328eceb
    md5: 85c6790365c4854d83ccd149d6917648
work/ice/RESTART/iced.23900901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23900901
  hashes:
    binhash: 7706cdce8d29ab8240a55ece07d76aa4
    md5: 55752a0ffd560a9ca9a078a9280fc859
work/ice/RESTART/iced.23901001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23901001
  hashes:
    binhash: 3cfe15c6aa6e1169b8c45f5edf7649f9
    md5: a4c83d2978c95c325a301b4436ba3c08
work/ice/RESTART/iced.23901101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23901101
  hashes:
    binhash: a0c471ef306c2b441c22919cfa5356f9
    md5: 6720e04bb233c29a9164e66f40dd437c
work/ice/RESTART/iced.23901201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23901201
  hashes:
    binhash: 9aa03989122bc16aae745a09eaff9f68
    md5: 60d385f975ebde06bbc44dc0d5a6c19c
work/ice/RESTART/iced.23910101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/iced.23910101
  hashes:
    binhash: 614e9772339232a3f28c56cc5d6bd385
    md5: 2447ef6af4f9afd1b71a5ff177de99b0
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/input_ice.nml
  hashes:
    binhash: 54b69999e084e5bf337da8b0c35320a9
    md5: 271bc9b86ff748b3f017baf77f2e4a0c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/mice.nc
  hashes:
    binhash: d464de296d477e6bf7f1e112a76fd915
    md5: 691eb336d38e60a7f7928b72253dee58
work/ice/RESTART/reset.iced.1850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ice/reset.iced.1850
  hashes:
    binhash: ec44efcdd810ad3940b6f29b9ff1475c
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/csiro_bgc.res.nc
  hashes:
    binhash: f0f7e0291309912dc385a56f342d7ed8
    md5: e47b938158cb7660af652a7c7df7e85f
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: dc581f9a4b156e8c39c744fc3e99253e
    md5: 9849bb0afeb9dba5b8fd0db45e71bd6c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_age.res.nc
  hashes:
    binhash: 4ffb46120f9705e3e9ee011441b690f2
    md5: 9b085d370daf609c69b1147b3956cda1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4965fad3e74d24b77d8d70131e1583c9
    md5: 0c4933d6cc8f316e1d8685217869ba9f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 62e1813c408e0276488c1ab381e85beb
    md5: d0acb247c46ce6977739b537f6a6ca6d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_density.res.nc
  hashes:
    binhash: ce8ce2878b6a89d9de0ce3185ef2cd84
    md5: b227b433d3b926d93bcedad80add4b8e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cf7bfa73d8658c9ea66dd05a6b3b4090
    md5: a52cc4cc72b6a9ec694240782d1c28ba
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0e5456a34d98a7bd364002e3b162411b
    md5: 3558aeb1cfbf681ec1129b973b07291c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 36bcf7e417a04a3f61987a2676d12261
    md5: f69b31ae9b88bdc606832654af7cafff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 12b3487757270cd4de7f0749162895b2
    md5: 723622ecc1cc4117ce5d64c4a9029325
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 775ce608d50ce6475e43847e3978cc20
    md5: b4ba74632cb6c161b45f25dec025ada1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d4e0ec51e04aaac5b341f4bd918df851
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_solo.res
  hashes:
    binhash: 02b27e268e13b536c653442ba3458606
    md5: 8c42895e91de726bcfe025989671c3ee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c43b5c68fbb69bb54bc26d8661a43848
    md5: eec69060dfd4c13da28b0a5231617358
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 805dbe467823f55fcee0a2062a1c37c1
    md5: 98d53e9d6b3c2aa45a0770c43a0761de
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_tracer.res
  hashes:
    binhash: bfa8dd7248348084dacaa1f82705d752
    md5: 0751be298f9a3a2e98dadc764d344512
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fe227d3e1fc3b76b52f70c8dea9c0823
    md5: 6f21c90dde3779f50a0be0f31773bb18
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-historical/restart001/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dc1af86f0b61ac05134dd2155424dbd6
    md5: 4838174596f162d9e420d6c8a5c6dda9
