format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/atmosphere/restart_dump.astart
  hashes:
    binhash: 033a5f6dc4ff9c4aa80a9ee2153f2933
    md5: db9a98971b9005584f6d2baf4eb13b0e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/atmosphere/um.res.yaml
  hashes:
    binhash: 5c60b1ee7da5942d0b1f5241c298c79a
    md5: 52ceb33afa46259905cf6d9bb5bd1376
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/coupler/a2i.nc
  hashes:
    binhash: 7c1755b69c14b4423eb8764241b1d3d3
    md5: 8f0f538043f66e814752cab90e33f565
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/coupler/i2a.nc
  hashes:
    binhash: e157ca5d8a12d0e4acd30084bfacc531
    md5: f963cb11dd52487b4c13a25e7731d244
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/coupler/o2i.nc
  hashes:
    binhash: 19538fdb1eb337834f7b3bc5bf7daa98
    md5: 18c5608a1dd466f1eee5bec1141319f1
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/README
  hashes:
    binhash: 464d97725152aabd14c7813eb4f2d02a
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/cice_in.nml
  hashes:
    binhash: fe101a42b3d182d7cc193ff9b56f05a2
    md5: 824ccf40bae1d6140e206c6d7ab370ee
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/ice.restart_file
  hashes:
    binhash: 08aa237014d3f0962d8fcfbc44612a78
    md5: 7c69093c5bf4bb69ef3cef5fc2a8b4b2
work/ice/RESTART/iced.19230101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/iced.19230101
  hashes:
    binhash: 4b19feacb38656bdb220be7a0a4e9043
    md5: 7de3a95577881729940fdcb1776e8aaa
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/input_ice.nml
  hashes:
    binhash: d50c527bae7bedcca7342e832a56b011
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/mice.nc
  hashes:
    binhash: 8fb3e5a3481b89a1dc20862fbba3ef04
    md5: 175a6a7dc04bc62b74255a4b3a5f65b9
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ice/restart_date.nml
  hashes:
    binhash: 1fb4eeb9b1a1e825be08ed66a03897a2
    md5: e8973fd362befe90913a7bcaefe267eb
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/csiro_bgc.res.nc
  hashes:
    binhash: ad53f873eed47a6ee82b2fbda431e628
    md5: a997a879c54ff02814edf26587f14405
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 22449a74bbf2226abaa2e26956d5394d
    md5: 9c2487b741023b8eb99102085e06e592
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_age.res.nc
  hashes:
    binhash: 9f70a329af2803bb887f6f7eb08f69ef
    md5: 54340559130dcd98aad871a9826d15a3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a92b8b3b4440ee2500b2f7d22129429a
    md5: 41e453148bc45d43472b46613559cfbc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 29e39c905fa4175e4e5daa2750577c6e
    md5: 005c0d48fec1dacc3e5c64e98b5f6b04
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_density.res.nc
  hashes:
    binhash: 3d238ca2e5adefe6b4db1d2c8dbea4e5
    md5: 54d1e9a20be01e4143fc94bce73cb259
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c7b1b73b581c92d4e6d359df67b0b71d
    md5: a2c2874fe5e73188953afffd6b270cad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 93ed03fa64cdeb4e6c0693812777dafb
    md5: 67b97065e035798518e3f0da069ca764
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b52e9112421cda4af90406e6a06de4e9
    md5: 98f0985709ed05d80948eed238a9e5f2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d883c1a8886c64d73537774e7461fc60
    md5: a62c6916df5c1f747552ab23586bb0e8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2409491f78d332dc260d19f713292707
    md5: cf4edc4d587e2bd49610974bdd3a5adb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 51774bec9e485f9293709a7379e98b91
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_solo.res
  hashes:
    binhash: 78ba084c507920f503d912fb2b965ada
    md5: 0c304280481c33fb56227bef627abde6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 02a41b5ccb180f7a7d72c8d1d02ed832
    md5: 0170931376eedef7af7386e4b8c7cfab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 26488a74dce00a2b6329757281f24387
    md5: 091c61811b1e0ecbb3136217e3a6404d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_tracer.res
  hashes:
    binhash: 79389cab3de9ea8da58478b7026f5c63
    md5: 3bc741fc313739fadef45db0c427bcba
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ca6e19a317455ce32b1fb89c07f8a35
    md5: 742b4d91734704f35a84068c2cb477bf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart072/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 622d24d5408de84e44a74517cbdf2098
    md5: 6e804ed69b355789913b6676564534e3
