format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/atmosphere/restart_dump.astart
  hashes:
    binhash: 4e58b064022c1135e075caa73f0b8444
    md5: 4c66768d9fdd65774b83c9376e1dfca7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/atmosphere/um.res.yaml
  hashes:
    binhash: cea04bd7a1364c3aec3281e53d3fc270
    md5: 1afa1dabcec6d8eb53d04eb99034311a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/coupler/a2i.nc
  hashes:
    binhash: 36d14491ed874574849415c6b0592167
    md5: 001f12214f0c09bd53a4a1a8e91994c0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/coupler/i2a.nc
  hashes:
    binhash: 629146b3bc52bdd04ff649e645e0ec8f
    md5: deafc5ce5e8fdaba097de21e3404eac4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/coupler/o2i.nc
  hashes:
    binhash: 66f2febc318efb6d6db5c63846902128
    md5: 9f0d0863d16eb0bea4588f4fd4be2fe9
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/README
  hashes:
    binhash: 9d54a6ef26f73198b22061e0769f96a4
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/cice_in.nml
  hashes:
    binhash: 65829cc283c633f459e37551fc0647c0
    md5: 814274fd79e5de414871c17121b1f614
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/ice.restart_file
  hashes:
    binhash: d543e2141dc3d6ac45cb78f44b666ba3
    md5: d70ec64da88cd8ebf0f5ce9e5bc08df5
work/ice/RESTART/iced.18970101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/iced.18970101
  hashes:
    binhash: 3ee6e18a9ae0fc191c06d5845ca13a2a
    md5: 55d951812732190278d3f9c9d7454947
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/input_ice.nml
  hashes:
    binhash: 84fe5dffc9526088a996da697c57cd16
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/mice.nc
  hashes:
    binhash: f82a554d2160f8b665dfd42474287942
    md5: cf847e952a0b6fed423e25c898a06810
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ice/restart_date.nml
  hashes:
    binhash: ea562ae353e85de879ed7a4c15bfaa87
    md5: ae1b3ceed3d0aa043d7b7f741c02d36d
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 5752e4eaaf66e4b56f7d71324ff87b08
    md5: f2860b9b04ef39d995fe6a03f9382e7f
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 1c582c0413b7242badb4a2c9086c6446
    md5: 4261f48d7e5ce5d2c121de59b61d6251
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_age.res.nc
  hashes:
    binhash: 0e72710e4b1343914eaf745ea8acffcb
    md5: a1d90c1e7143f788ba4cd4f43bf7e53d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2c73053273efabbf68f8697f02e8dbef
    md5: b8ba243d33ab56822dacf6b570903677
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 240145d9e9005d0eaac6929348b972cb
    md5: e310951911d6805aed3f41d128285185
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_density.res.nc
  hashes:
    binhash: 7e6cb61538e3c1484d45725487937cd6
    md5: 783350d0551a271fbfb6ac3ee06dc332
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9a96dab15b2e83625dacf5d1d72e4c84
    md5: e486eefba9f0deb6a3a963bf26ca911f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8a1cb5787616420469ee12803977fa95
    md5: bdb26f26bc41e0fdda80e7538bae638d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fbe6b9d1f365593e50f0ea3d0b0dc46e
    md5: 2c15a5c26775b869533eaf398dd8551c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6f7909912149f40282eb79d0d4eeef0d
    md5: d201d280fca6ed9474b293d2946d1103
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c7cba325b48bcc7f47ac63e958a41cfe
    md5: 79790cbf4a137ca1c7577bb2bc288e54
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e510cc9772e7257a4b8910d142604e8f
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_solo.res
  hashes:
    binhash: e42ec214c68a80b298160d280af36a9b
    md5: fa518322156457f5aa4f4906575f8532
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1eb6f425b350b5e67e83b30cac10cab6
    md5: df21a43517841d02ccec7552ed0406f5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 748d8557e7adfd536fb2951dc6e96da8
    md5: d6fecbf82befeca8a790226db1b1e384
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_tracer.res
  hashes:
    binhash: b33af714f141f4360977a91bd5029bbf
    md5: 3c95ea25bc47cf650b59fabc6a11c5d6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 68a945f38db22b0cda0a42ae36dd743c
    md5: cc4ff928b7c0556bc05bce62b0243e65
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart046/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d7a0ba51dd61b0990d5327c686375ed6
    md5: 7ce69a2f3741c6ff06a5a158ee4ec4f6
