format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/atmosphere/restart_dump.astart
  hashes:
    binhash: acc88fdea93ddcb1d643036469f5015d
    md5: 500ef8e653c4a7ba955ac15725b996bd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/atmosphere/um.res.yaml
  hashes:
    binhash: a48176b09c6c26d4b27bb22053ad30a6
    md5: c290a13581e218c5e58a2ca4fc25188a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/coupler/a2i.nc
  hashes:
    binhash: c05a0fdfd4f173066483a3b63878aaf2
    md5: 854bddf324d138d6fc7be315274f8cc6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/coupler/i2a.nc
  hashes:
    binhash: 957c87cb323234b9591cb12e0f8447e2
    md5: c1506e296c8aeae1233f271ca7a4cfbf
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/coupler/o2i.nc
  hashes:
    binhash: 26c5f0d5840e2ef1df54cca4a347f300
    md5: 3ffd3b8fa799259e9a00799d560dff5f
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/README
  hashes:
    binhash: 2bea761844bf8545d26aadac763fbeb8
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/cice_in.nml
  hashes:
    binhash: 92fb6dbea4d54641d9534a079eb1b4f2
    md5: 40d59a8d9afdbce2b505f025ac8044e3
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/ice.restart_file
  hashes:
    binhash: 527cb269f343b6cc3d1feb85610b5fa6
    md5: bfd8f4c705d7a7b9df01c0a2af3b1b8a
work/ice/RESTART/iced.18780101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/iced.18780101
  hashes:
    binhash: 33070023a9991ac85c6cd634c8a887c5
    md5: 0aba41dcb0cfdb68eda4eb53047cc437
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/input_ice.nml
  hashes:
    binhash: 7a83154780f804ca38b17b47c6c6c4dc
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/mice.nc
  hashes:
    binhash: 1d461497b03edb13deddaecdd4ca2003
    md5: 8dc57b20ff6efd4cd554f1cb4aa02241
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ice/restart_date.nml
  hashes:
    binhash: c1d815b3707209b50442dd22af1607b8
    md5: 635f97cea6c93a93b8b317776fe8a655
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/csiro_bgc.res.nc
  hashes:
    binhash: da259138de46fda44535f2380068916b
    md5: ce8b2178dfa5b3f3b49b89d6919f2f24
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 421da5237e366a6432f42d08c33c7333
    md5: b2c2ae0e6c86b9f4e1b1d70e87328cb6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_age.res.nc
  hashes:
    binhash: 3908f99684792e3ef78bf56e81a7cfde
    md5: bf1ce4614bc093270a968e97262d6f3b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 54c974545b57a8e5b23061e1d6b2efec
    md5: d8078cfded8d96803fe70b86526b23e8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1b1394a4d292071243f7b6315ebf82fe
    md5: 69feae4b4e33c47a1e86935e7172f3e5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_density.res.nc
  hashes:
    binhash: 8664d7d3f1ff3f672cf3fa282fbcb842
    md5: d56c88b1f6344edbe4771bd4f78cd5cc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1e732a58093a97723cbfe20c8e35cf56
    md5: 400376dfce2690f8c0b2b50344f58777
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e40e97e5afdd4b665fdc528ec2cefdae
    md5: eadf2879e427fae53fe46951f64876e4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bffc3cdbc7e18bd3a9ed80bae39c44a5
    md5: bd14011215e74d7bc3c7aa15c377b5d4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eb3d03b73ac68a232b84d0b1527f0927
    md5: 258d5fedd1a04658432736584ee4e410
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 60bf0b75a18283225d5837a57042f574
    md5: a4ff4ed693209658e609c3855a2f95f2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7f661d00d30c0bfac0761fd5b303584e
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_solo.res
  hashes:
    binhash: 84a85886dcfb859e41c1f340cb26fe76
    md5: a455e050a74c20eecd39fabc14324de9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 841c441eabcc7fb37d3d2d4c2abf47ae
    md5: 9139a044f4ea5489327aa395bb308b68
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5cac5d49fe013b9955baed9ed870e925
    md5: 1c57c125e19d2ff4b8647895a9a81c62
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_tracer.res
  hashes:
    binhash: d4d22a13ed97dbf74a8d1bd51ddb8721
    md5: 024d0ca46d62755cd905496c05f31c7e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b10d28416650752231bd27ae680ccbb8
    md5: 36c76d16f0efb56f1b2ac6654162928e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart027/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 01f10c47e8effa21ae37e5934012caa7
    md5: 4d083f31acfe3f8e0d61790e1d7638c4
