format: yamanifest
version: 1.0
---
work/atm/CNTLALL:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/CNTLALL
  hashes:
    binhash: d682808f86aaeffbe66d5f5c86d878c9
    md5: f60b5e03683f4c72cc3fca47a0e16f40
work/atm/CONTCNTL:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/CONTCNTL
  hashes:
    binhash: ee0a6be58cee0d5e98b26cba068ce5e0
    md5: 7125cdf5fd041856bfefce47256ea2a3
work/atm/INITHIS:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/INITHIS
  hashes:
    binhash: 06536bd30a0087bacd8bc04c800e6c65
    md5: d0d6100c39ef0dde8d4106316bbe8703
work/atm/PPCNTL:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/PPCNTL
  hashes:
    binhash: 92167b39663debc0369fcef5a1629545
    md5: d41d8cd98f00b204e9800998ecf8427e
work/atm/SIZES:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/SIZES
  hashes:
    binhash: 00def4a40e07a997110aa1041e28bb6f
    md5: dfa5d595a84c918ffb39b88a92b7a65d
work/atm/STASHC:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/STASHC
  hashes:
    binhash: 646fa09e642d0df421cd9b2cb820c140
    md5: a30e18080c39e4febfc730e244f03279
work/atm/UAFILES_A:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/UAFILES_A
  hashes:
    binhash: 025401f8146e48cc6e682f659e16a82d
    md5: 89de66fc629bbf4e39994b433f737f60
work/atm/UAFLDS_A:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/UAFLDS_A
  hashes:
    binhash: ea205ad3cab0306720f347e1aacb2b43
    md5: 42abdb31b6953d994d7c31125bf025d4
work/atm/cable.nml:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/cable.nml
  hashes:
    binhash: dfbc39ee9d729bd39381cf4869e7de30
    md5: c41274e9e915be62b01ad3c88d012628
work/atm/errflag:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/errflag
  hashes:
    binhash: ae05952c4f10658569c97262fc91c7e6
    md5: bb5517eec4fd1a0ab152958f702a366e
work/atm/exstat:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/exstat
  hashes:
    binhash: 6d79a47177aceff5e1e15e7f28cb343c
    md5: 9c8698bf0dd61c4390226dc56621204d
work/atm/ftxx:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/ftxx
  hashes:
    binhash: e1caadda57e7ed9c2cb3062712a24243
    md5: 68b329da9893e34099c7d8ad5cb9c940
work/atm/ftxx.new:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/ftxx.new
  hashes:
    binhash: 579a1cae653b9fe9c856badadf06d7c4
    md5: 68b329da9893e34099c7d8ad5cb9c940
work/atm/ftxx.vars:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/ftxx.vars
  hashes:
    binhash: 9ab7abd12bac290b3e074f0615083963
    md5: 68b329da9893e34099c7d8ad5cb9c940
work/atm/hnlist:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/hnlist
  hashes:
    binhash: 13b46a4515451263344323c3344adb06
    md5: 987f12c9925ad0c5934d84d4b1b3ba34
work/atm/ihist:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/ihist
  hashes:
    binhash: 0bf5e4a5ed454de6889401db9d8998db
    md5: 919469b713a0d0c030e6186363be1201
work/atm/namelists:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/namelists
  hashes:
    binhash: 8c1b8b2c4ed6a1451c1ee41ef8fe2fcb
    md5: 984fc7aa9ccee61bd69a2c5081bd037f
work/atm/parexe:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/parexe
  hashes:
    binhash: 57e1f0637799b8fb47925477ea57a216
    md5: d41d8cd98f00b204e9800998ecf8427e
work/atm/prefix.CNTLATM:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/prefix.CNTLATM
  hashes:
    binhash: a42d31df45b225073fe99999242d3b0b
    md5: 68b329da9893e34099c7d8ad5cb9c940
work/atm/prefix.CNTLGEN:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/prefix.CNTLGEN
  hashes:
    binhash: 1d8863ca0ee78ed27b2d4eba2d6349bb
    md5: 9410902eec47522582286e062d10ed81
work/atm/prefix.PRESM_A:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/prefix.PRESM_A
  hashes:
    binhash: 046e0f008df93564722660f59734726b
    md5: 9e3c40fb0e4faea3bde157297a8f9208
work/atm/restart_dump.astart:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/atm/restart_dump.astart
  hashes:
    binhash: 42ff26e0a8b67b40696f88f7c47e7432
    md5: d1aade65c4cdbba98bb7be7cef345f5f
work/cpl/a2i.nc:
  copy: true
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/cpl/a2i.nc
  hashes:
    binhash: 8bd52f0e4ca7697014322151917b7d78
    md5: b0bde4825aab75b31150e1e3a0fe3c82
work/cpl/i2a.nc:
  copy: true
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/cpl/i2a.nc
  hashes:
    binhash: 5d140d50034ef422af3a34b9fdc1bad8
    md5: b8dd54273d0870c7883329ef40694afa
work/cpl/namcouple:
  copy: true
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/cpl/namcouple
  hashes:
    binhash: dea75a116ac085a8ef6956a6816cbe4d
    md5: ed923615df8dfa5839aa5c08933ef1ea
work/cpl/o2i.nc:
  copy: true
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/cpl/o2i.nc
  hashes:
    binhash: 1a63ff820e061e5fb06c81fcba94890a
    md5: 222878a05edc75965440268007c6376c
work/ice/RESTART/cice_in.nml:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/cice_in.nml
  hashes:
    binhash: cbd481f89fed58f197d2670f834361ff
    md5: c97bd9547ec0c48d1bf1e3ad2860868e
work/ice/RESTART/ice.restart_file:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/ice.restart_file
  hashes:
    binhash: a6f1f759bf30e10da8ef53ee3bb7b5a6
    md5: 5336e4cc6d3c7b486c1178db2a4ed36a
work/ice/RESTART/iced.01010101:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010101
  hashes:
    binhash: c6a7b1b002c101985b0ea5fc7df467be
    md5: 9d1c203156e0c6d73ea9ed909c6d174e
work/ice/RESTART/iced.01010102:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010102
  hashes:
    binhash: 8f843dc1543f8b06afbe31bea8dc71ff
    md5: 36cfe461f5fa35837616c8befe7e096d
work/ice/RESTART/iced.01010103:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010103
  hashes:
    binhash: 46f14a5e68c716b88ab26bffca3a185a
    md5: 03741491c08d334e764bea9c562d1671
work/ice/RESTART/iced.01010104:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010104
  hashes:
    binhash: b30e1a1b3ffda9ab78a697035c0ce260
    md5: 9afd901a559e5d4a7a4a8216ea71eb40
work/ice/RESTART/iced.01010105:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010105
  hashes:
    binhash: 27a043058dd48a92b022d8085649b280
    md5: da65ef56235755fe45fd9a3d73a3149e
work/ice/RESTART/iced.01010106:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010106
  hashes:
    binhash: c6f5da04053b13a0a0ed40d435507546
    md5: 45aef69f3cc214fe47f70ef5ffebb068
work/ice/RESTART/iced.01010107:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010107
  hashes:
    binhash: 24b5f9521e6c15055d786c28346e5924
    md5: f2edd1ed84f090543cb18f459fc5ada2
work/ice/RESTART/iced.01010108:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010108
  hashes:
    binhash: 7be1b903483d3d497d77086aab67180e
    md5: a426fa7a988c068f6d06ccaea026c325
work/ice/RESTART/iced.01010109:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010109
  hashes:
    binhash: e99e4b2770daf9dfe630bef3ebaefd00
    md5: 7360b8a8309c6c27d74f2e26ebe3dd76
work/ice/RESTART/iced.01010110:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/iced.01010110
  hashes:
    binhash: 803bb34421c5ebc5181794ccfbac7fbc
    md5: 2643f2447f100473070f368699281783
work/ice/RESTART/input_ice.nml:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/input_ice.nml
  hashes:
    binhash: ba9f40c3f72ee22c703a1e83cd15910e
    md5: 9386de0d967d45da07ee1876b3d11ffa
work/ice/RESTART/mice.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ice/mice.nc
  hashes:
    binhash: 97ac4e5fb84cb94b83415755aa9939f5
    md5: 123bad5365f88398eb4d09045a0785c1
work/ocn/INPUT/csiro_bgc.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/csiro_bgc.res.nc
  hashes:
    binhash: f1c0a6e41beca5ef445cfd51256400fb
    md5: 04f35ffa46dc128fa9dadc4e505b538b
work/ocn/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 53a9662fcd824cd4fbfae79c94e38d48
    md5: 416ae6212907ff876c544c8181e1734d
work/ocn/INPUT/data_table:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/data_table
  hashes:
    binhash: 83ef8f534fc92d9b62856b1e7ba146bb
    md5: fbd3dbd9e26ed4e20230ebbc550076db
work/ocn/INPUT/diag_table:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/diag_table
  hashes:
    binhash: 0b3b0e6b2a1577e0ef04642b11d905d7
    md5: 496f9fcf67e46b1a95bd6117daada95f
work/ocn/INPUT/field_table:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/field_table
  hashes:
    binhash: 03b2f13dce4c0b2e11c9b6a809247ab8
    md5: 32c61c4903cb3e487358624f4b486066
work/ocn/INPUT/input.nml:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/input.nml
  hashes:
    binhash: 18cb6783961706edbaec58aa7ba8df31
    md5: 54eb570194f279ddea887146336480b0
work/ocn/INPUT/ocean_age.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_age.res.nc
  hashes:
    binhash: 88099504e786a73f17624491841e41df
    md5: 8b4f87b0194af48125b0ae486546b9b2
work/ocn/INPUT/ocean_barotropic.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_barotropic.res.nc
  hashes:
    binhash: 722f44b722b76f04baff307bd5c001e2
    md5: b3da4d845641e11d273bb5163cbb70ae
work/ocn/INPUT/ocean_bih_friction.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_bih_friction.res.nc
  hashes:
    binhash: 98553b7ba0f8b1363cdcafc6be62a6b1
    md5: 3d71c94edeab797fb9cdddd9cae5c2a4
work/ocn/INPUT/ocean_density.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_density.res.nc
  hashes:
    binhash: 902fe863d02d97475fd108b132976483
    md5: fd2df986d8f304161324fbe9e9e2c908
work/ocn/INPUT/ocean_frazil.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_frazil.res.nc
  hashes:
    binhash: 1ca696b017bf3d9c7dbb7f01a5ddcccd
    md5: f71d1267c86449623a43ca9c5b11c8b0
work/ocn/INPUT/ocean_lap_friction.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_lap_friction.res.nc
  hashes:
    binhash: 1e31e5698dc984daee2f93b4afaede7e
    md5: a382a68d29174c8cd3180397306dea9d
work/ocn/INPUT/ocean_neutral.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_neutral.res.nc
  hashes:
    binhash: c9df1e2cd899d3aa538ebe8102cd1f7e
    md5: 74fcbb11f3c375e192f3f65f57c07fd5
work/ocn/INPUT/ocean_pot_temp.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_pot_temp.res.nc
  hashes:
    binhash: 4fcd127bec011907b28155ac8196937b
    md5: 836b557238fd5202559ee092ad55c94b
work/ocn/INPUT/ocean_sbc.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_sbc.res.nc
  hashes:
    binhash: fed5e9d24781f082ce42d3678e6fe449
    md5: 129ac326ee92564610a00d7262b1dee3
work/ocn/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_sigma_transport.res.nc
  hashes:
    binhash: a1bd37b8fd763de9de2cb87204eab666
    md5: fe527a9917d30955d0dc082271c1392f
work/ocn/INPUT/ocean_solo.res:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_solo.res
  hashes:
    binhash: e9e1dce3300884e0f15568b7269b4d32
    md5: 78b5165334194905dc029bb04a7db48f
work/ocn/INPUT/ocean_temp_salt.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_temp_salt.res.nc
  hashes:
    binhash: 98f38a825c4c3e87ea540a7d577bd829
    md5: ee902392f4dbcbc102393384715fcd64
work/ocn/INPUT/ocean_thickness.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_thickness.res.nc
  hashes:
    binhash: 69469815015c2b47a8d84292a925e6f2
    md5: 2fc1e8d516a14dc8c11ee5363b194c5f
work/ocn/INPUT/ocean_tracer.res:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_tracer.res
  hashes:
    binhash: ba205de6b3d1516c42d6ee5a4fd2f051
    md5: a96679f46fa099fdb6962ffc65492427
work/ocn/INPUT/ocean_velocity.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_velocity.res.nc
  hashes:
    binhash: 067f6ba4dd5357efd929faf82a1c20b2
    md5: 3107181d6f1f99b27ab737ab3c7873b0
work/ocn/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /short/v45/aph502/access-esm/archive/pre-industrial/restart008/ocn/ocean_velocity_advection.res.nc
  hashes:
    binhash: 17885e86ac70cda5e00dc2367034ecdc
    md5: 4bb13a0fe2bd06bb1032852ba8c02a43
