format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/atmosphere/restart_dump.astart
  hashes:
    binhash: 06847112a8d219139f760ee4985f3f3f
    md5: e7a01179a783e94960065b52b9fa7caa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/atmosphere/um.res.yaml
  hashes:
    binhash: 4475ff450914839b64b47aefcba4a3a1
    md5: 4f7a496c69b898777ea3958404bd5cd0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/coupler/a2i.nc
  hashes:
    binhash: 39745084fbded0be2df660445d9e9bdb
    md5: 5eb3527cb3eb848029eeee6f4bcef331
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/coupler/i2a.nc
  hashes:
    binhash: 6beed6e8b59d8d6feffd9e7df18feb94
    md5: 77d956724c13dd8486f703c2bb425321
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/coupler/o2i.nc
  hashes:
    binhash: ea5561f329d6d4717156d85d08c55c55
    md5: f01abc40f4456988ff4ce921b4c09b68
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/cice_in.nml
  hashes:
    binhash: fe4c17fc3c20125020b5aab5a09557a2
    md5: 8959a2a790d13c91f70322a9ec2f2097
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/ice.restart_file
  hashes:
    binhash: 22fc05dc77d74cb65a8159a08dddf477
    md5: 57695854a21c24c7998d59b8b32a7543
work/ice/RESTART/iced.01020201:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020201
  hashes:
    binhash: 78527ad7a9e5724b362627020f7a50c7
    md5: d6276f1486a507167463ea74a5f53a15
work/ice/RESTART/iced.01020301:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020301
  hashes:
    binhash: bad4fea675dc35ee3f0d70194c6ec975
    md5: 29645e3a622b86372911d493802d1619
work/ice/RESTART/iced.01020401:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020401
  hashes:
    binhash: 7b7da2d7f14eded16afd50a498dacde6
    md5: 569d0ba9de470f5234ca97d5bb141a80
work/ice/RESTART/iced.01020501:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020501
  hashes:
    binhash: 6c8e1a7b16b6698796ea7c23a962a912
    md5: 14be85cbc32a57a80bf50dd9bcb5b02b
work/ice/RESTART/iced.01020601:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020601
  hashes:
    binhash: 3098d2e45073601c1d733752527792da
    md5: e7ccacd99980c2fec4ce9c9b90704630
work/ice/RESTART/iced.01020701:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020701
  hashes:
    binhash: 59289d852067add901d85dcbd3332388
    md5: 1440c5c242b22ad7cc57fa92ce5461b6
work/ice/RESTART/iced.01020801:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020801
  hashes:
    binhash: 3d174f0d78df9005a33f59fb7a97c87a
    md5: b167ec9a29a889894ec2c2ab13a74850
work/ice/RESTART/iced.01020901:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01020901
  hashes:
    binhash: 80002648b45654b9fddee8ff564d59d8
    md5: 8ec0e628566de7c895299c0ed79433dd
work/ice/RESTART/iced.01021001:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01021001
  hashes:
    binhash: 248658692ce542a15a489fb8fb137d0a
    md5: 28d3c37a7e82217c575e4065fd4a3d82
work/ice/RESTART/iced.01021101:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01021101
  hashes:
    binhash: fc35fde356f037b127f31764c41bc582
    md5: 14746b30d24c81659dd149e36847a1ba
work/ice/RESTART/iced.01021201:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01021201
  hashes:
    binhash: 6e51740d0d0d3ca9bd25044a11dbb6ca
    md5: 8fb44fdaf17ef2aff3dceea114172947
work/ice/RESTART/iced.01030101:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/iced.01030101
  hashes:
    binhash: b06b43ed8b13dadd51ca39f67559608a
    md5: c9bfcf57719bac308596607250f4a565
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/input_ice.nml
  hashes:
    binhash: 01ee7f02465aab2a0a241834050556ec
    md5: f28a22cbeb7d4c11c9f8a8be3698d918
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ice/mice.nc
  hashes:
    binhash: a0df05698220a3b7958060ab8e2a1fbe
    md5: ea5f24638c6f80e75e4e7c554a202ed7
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 286eccc996686d1dbe4b0f255dd81333
    md5: b3e0cf1397976bae4a9eb7756d5dbee2
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 4314607901676b802c7a8c2a9b801e17
    md5: 1da20b6045e11388cad1faf460ff6f8f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_age.res.nc
  hashes:
    binhash: 5be4f27cff5700a816d7fe80ec2eb0f4
    md5: 14b2ee210d8a7dce4ef1a1550b4c91b2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 65be04c8f2f60f61a79fe1ab8012e9d6
    md5: 98e237436f4382efc472fb2145b0c21e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7a2de27adea3f44a0a659f484c744e91
    md5: 35d675fcbdb7af04a8e512df5618e7b5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_density.res.nc
  hashes:
    binhash: 5fa24f28003d6b096277a58c69a6e2fa
    md5: 02c333c0ced8166e3a48697353bf638c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4b2494372294bfb3e387a04e9ee1e0f8
    md5: 2b23bc5c27095db8b5365a654dfd35f4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a4df07743d8efe92ae6395650ef85612
    md5: de3633112b387091b9b750a39b81439e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f717a30499350af6e8b2b99a9c7b680d
    md5: 1faf691b868a99926d97b002cc3dd01d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ffbae6c4785c7a2d6441e6336198f8ae
    md5: 161d7b86db0370989b99d85afe5b137f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9b9606b2009026cf9f99ebafea97fc88
    md5: 66d7cf4ddbe456d6002f29b2e37ca616
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7d706c9a1259723e7cc7b2bb7765e146
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_solo.res
  hashes:
    binhash: 5a44ed007f56355a312fa2e32887decb
    md5: f191d038c188c7d83f529927074f1472
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fa3c09461bd166635617094b8895d5a1
    md5: 989d76f4f024623adc038b088461d7e3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8882b3f3670616297c965e3acdf3e42e
    md5: a1343b9661bfae613ab8df22169788cb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_tracer.res
  hashes:
    binhash: a60d18ab3fb4d812aaaabd0a2790f611
    md5: e232b0d2fd521279aa422895f1b5e5d0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3a125315d9082e4929925d2bc896cafc
    md5: a7e2b1faebd190063546a71ffefbf6fd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/esm-picontrol/restart001/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0f57db0bb16d98713444abb839e442a7
    md5: 128d385bf91110baca407d34050b1951
