format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/atmosphere/restart_dump.astart
  hashes:
    binhash: f16fd16f7250189ea434f9501625a26e
    md5: 8f6ec0f094c622bbe1987946acb21db0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/atmosphere/um.res.yaml
  hashes:
    binhash: 142ece4eae15d61752ba666c7d989f1f
    md5: f77ffc4445b2fb33dda20fdc697635d9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/coupler/a2i.nc
  hashes:
    binhash: 0abec221e63405c655adc3c4dee8416f
    md5: e6d5e25d7846f0fd173895571b60bac4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/coupler/i2a.nc
  hashes:
    binhash: 03e8128576df4edd0d256dda58e9cca1
    md5: b34db8ff710c64aed1c987d2c075bdc2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/coupler/o2i.nc
  hashes:
    binhash: 68112247a008f81748c9a5838f89b16f
    md5: fd70a7b0ddf20bd295f763fb6c3885cd
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/README
  hashes:
    binhash: a545043473bbce66610bf1e6c6cf84a2
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/cice_in.nml
  hashes:
    binhash: 3732104c176d35d0920addcd60026812
    md5: 03bf063774d3914e61b3249b3cf5b7d2
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/ice.restart_file
  hashes:
    binhash: 058a832b6614c43fa89fcf724e699a99
    md5: 60dfee9ba555df855d1b5a5b60a09006
work/ice/RESTART/iced.19030101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/iced.19030101
  hashes:
    binhash: 6da72dd6e2a331f2ca2aca61cedbebe9
    md5: 955e835196775d5f083cb63f119e8bf6
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/input_ice.nml
  hashes:
    binhash: d102108664ee7ac96c1ea6740bec906e
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/mice.nc
  hashes:
    binhash: 5feb9467a3912c0aac6865abbc2fe514
    md5: 51c19ab1d3bb23a89c2476dde4abe69d
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ice/restart_date.nml
  hashes:
    binhash: 6a86b8226c721174e8a60d88a0b290f0
    md5: 4caee63c67ad7888d801fdd61a2577c6
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 03ea88ba54727affbf0492bb23543f77
    md5: 52d0b75ecf5a06c7501d604f336dd856
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 5d3fa18cb747c700beeb36b06fd01c7e
    md5: 4613a30bae56091302e80a553402689c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_age.res.nc
  hashes:
    binhash: b34f273e9a2cb055557249a29c1fe36d
    md5: 32dc8fa4209c8670a3bd0a3d45d0ff17
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 93087aca43e710f3464ab06120ea167d
    md5: e0f5a49db2f45862a0146421cf0ea5d4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0c9e0b861d7b960577f273f78f494c76
    md5: ffd35b455444ce466d1da9c8a34d1eb4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_density.res.nc
  hashes:
    binhash: e9fcb51ce1b7086c8160674edb18db12
    md5: 45f403fdbd66129950b41a6a9be6b1fa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 57ccd9f65f0d8dc98df7e5f2ab70ad5b
    md5: b7e08256781e8fac7ec95c68368c058a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4d0e2f2fa93e6bd221ff938f0df10b54
    md5: e6154d9f0b2b49d67d2288eabae9b687
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2664565b8cd5c31e558db9e36e2ffa73
    md5: 54d345d86032001d57b8bcfd565593b0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a11f1d087de8e743a2115bca809e819f
    md5: 1b736929961488641c714ecb2a343cab
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e1d8743a09a8b477d1418b10fe1be5b7
    md5: 79e4177fa3871794c4c5a9fc5c5ed77c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f7ba71d1fbe1994a8d18615412a5875
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_solo.res
  hashes:
    binhash: 55453fafec4944e3afc24b965e7c7fcb
    md5: 8df699493fcbc8b808e08d96d5ace73a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 059390058466587d69a52547fe25e329
    md5: 98b1a7b068828fea251f6767019bd699
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f1c2249015ea4982f2ad9227f9406007
    md5: abeb20ce893376186bb4571c5653d2d1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_tracer.res
  hashes:
    binhash: cccba06edb23878247b65cfffd558b20
    md5: 709158a5d4e93c19d235765ae8e6afb4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0970457cf0b41f5ae1488ebe5c58e832
    md5: 45c2a3da9965a28fa2b02508bec6da81
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart052/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f3573e6814b6d5be1f2fd5888426de88
    md5: 21373b393dfa925e6be2cb097f0a0274
