format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/atmosphere/restart_dump.astart
  hashes:
    binhash: 8c0ac1f3885d87494ebe2504ccdd3d60
    md5: c4db749778f687eb42c19fbed3815bc6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/atmosphere/um.res.yaml
  hashes:
    binhash: afa4a164d085fda4b668bd417308f695
    md5: 62bc6c2a5bf0a74c8c30057cea08bb1d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/coupler/a2i.nc
  hashes:
    binhash: b914f29feb18bbf054cf96f76f5ecd06
    md5: 8f8317f60a35d5da215c9e79ec7b6367
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/coupler/i2a.nc
  hashes:
    binhash: 92541f14890a796e3e66b9c2fac3ba4e
    md5: be280cc42e505a5d4d535a5588cd8451
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/coupler/o2i.nc
  hashes:
    binhash: 7b1ebeefd1dc0dbaf1ec14d6eb361430
    md5: c6d4febf98441ddeb241d694ac30a142
work/ice/RESTART/README:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/README
  hashes:
    binhash: 925398f1a210b3e7508abfc034447d79
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/cice_in.nml
  hashes:
    binhash: 6d1f9eac94c2f88f9445083e5515518d
    md5: 8564e68e335a4cff21e77493cab9736b
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/ice.restart_file
  hashes:
    binhash: 32c78bb24035f7c6af9370a4e4bfab9b
    md5: 49df3c52ab199d7b6164846119abdb83
work/ice/RESTART/iced.18980101:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/iced.18980101
  hashes:
    binhash: 6f70f05ecd74ca1c4d8fb54e108b5412
    md5: 177378b8520e56b5747683aac652ebe8
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/input_ice.nml
  hashes:
    binhash: caaf4fe2a2e6d458cd857e14d0aa58d7
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/mice.nc
  hashes:
    binhash: 0dad35924aa75788fd44128e500b4ea0
    md5: a0c24ffa0caa666fed93e7ce48c58b60
work/ice/RESTART/restart_date.nml:
  copy: true
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ice/restart_date.nml
  hashes:
    binhash: e66ef51912298448e04ac4234f797218
    md5: 4c9fe9426136712c34abb630465137e5
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/csiro_bgc.res.nc
  hashes:
    binhash: f37c611744168b9cbe8158e142585b32
    md5: 5590678fb0d2b85f4be142ca5b6c30fa
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: bfbe34386add75202358374027bb60d3
    md5: 970e677bf8366f94d22fe2854fac2877
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_age.res.nc
  hashes:
    binhash: 0325da735d6707115523458aca4890bc
    md5: 941c2c7fdf748aba4030c488387a6cea
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4508eb43e5e99b08af8ead3b65709592
    md5: 4f4b297a49b903a17b52074a103269d7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1c11949b325cd8fae12e513d85c19a34
    md5: 5fb164e691539b2ba1b4d20f42077285
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_density.res.nc
  hashes:
    binhash: 16849cd66cfc61cb5488ccc2712bcd10
    md5: 28cf8e2c1a720881c181882d99dcdaea
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 721677a2848fd197b474d4a6d5aeef18
    md5: cd7eae2777d91e871a0193ab7c3ebbea
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7bab7b528b142a12ff14ea936a956f77
    md5: bd32edcf73b6b589a11ab31a06c5750b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c770700152b41050fb0ead344800aedc
    md5: 20ac47738623a564b39b63ddf5fd01fe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 971fdd0c6a1b63ca4b4ae3086c822f20
    md5: eb5fe23183d027232e19a213ada092d4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ee0780778ef29c5731557cddba11f66a
    md5: a38271f29693a4f978e6b3a51865e5df
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4c15df976f790f1ce41041ba0999f79f
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_solo.res
  hashes:
    binhash: b3a02b26b3630a8c34f722702cb45c39
    md5: 03f69cadf471290c05e59a7bdba37570
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 36891e2607847d2b0baae03fc3939c9f
    md5: 97c243f1928a4ab4b5d5841cc2db72e2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 65916fac567052bd0499bdb9db52ee78
    md5: 82800bd18986d516d5d3489417b1a110
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_tracer.res
  hashes:
    binhash: 527a5adba34a12eb323e8824f9d375f1
    md5: 2673d640e9d5348b3da2f7731f5a409b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c1b0c9e6d994192220b4cc10e95004b0
    md5: e1a179187ecb3837c348a01ae416037c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/tm70/sw6175/access-esm/archive/20240823-dev-historical-concentrations-run-20240823-dev-historical-concentrations-run-067ed4bb/restart047/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0abadde5f5e80370527b9ad3b480e740
    md5: a4aaeb583d99bbbddd27d7426b575f95
